import React from "react";
import BackToAllProjects from "../components/BackToAllProjects";
import CoffeeBarHero from "../components/CoffeeBarHero";
import CoffeeBarImages from "../components/CoffeeBarImages";
import CoffeeBarText from "../components/CoffeeBarText";
import Footer from "../components/Footer";
import Head from "next/head";

const coffeebar = () => {
  return (
    <>
      <Head>
        <title>Darko | UX Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoffeeBarHero />
      <CoffeeBarText />
      <CoffeeBarImages />
      <BackToAllProjects />
      <Footer />
    </>
  );
};

export default coffeebar;
