import React from "react";
import Footer from "../components/Footer";
import FurnicoHero from "../components/FurnicoHero";
import FurnicoText from "../components/FurnicoText";
import FurnicoImages from "../components/FurnicoImages";
import BackToAllProjects from "../components/BackToAllProjects";
import Head from "next/head";

const furnico = () => {
  return (
    <>
      <Head>
        <title>Darko | UX Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FurnicoHero />
      <FurnicoText />
      <FurnicoImages />
      <BackToAllProjects />
      <Footer />
    </>
  );
};

export default furnico;
