import Head from "next/head";
import React from "react";
import BackToAllProjects from "../components/BackToAllProjects";
import Footer from "../components/Footer";
import SneakerHeadHero from "../components/SneakerHeadHero";
import SneakerHeadImages from "../components/SneakerHeadImages";
import SneakerHeadText from "../components/SneakerHeadText";

const sneakerhead = () => {
  return (
    <>
      <Head>
        <title>Darko | UX Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SneakerHeadHero />
      <SneakerHeadText />
      <SneakerHeadImages />
      <BackToAllProjects />
      <Footer />
    </>
  );
};

export default sneakerhead;
