import React from "react";
import BackToAllProjects from "../components/BackToAllProjects";
import Footer from "../components/Footer";
import TheTomatoImages from "../components/TheTomatoImages";
import TheTomatoText from "../components/TheTomatoText";
import TheTomatoHero from "./../components/TheTomatoHero";
import Head from "next/head";

const thetomato = () => {
  return (
    <>
      <Head>
        <title>Darko | UX Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TheTomatoHero />
      <TheTomatoText />
      <TheTomatoImages />
      <BackToAllProjects />
      <Footer />
    </>
  );
};

export default thetomato;
