import Head from "next/head";
import React from "react";
import BackToAllProjects from "../components/BackToAllProjects";
import Footer from "../components/Footer";
import TravelLifeHero from "../components/TravelLifeHero";
import TravelLifeImages from "../components/TravelLifeImages";
import TravelLifeText from "../components/TravelLifeText";

const travellife = () => {
  return (
    <>
      <Head>
        <title>Darko | UX Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TravelLifeHero />
      <TravelLifeText />
      <TravelLifeImages />
      <BackToAllProjects />
      <Footer />
    </>
  );
};

export default travellife;
