import React from "react";
import AboutHero from "./components/AboutHero";
import AboutText from "./components/AboutText";
import CTA from "./components/CTA";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>Darko | UX Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutHero />
      <AboutText />
      <CTA />
      <Footer />
    </>
  );
};

export default about;
