import { Montserrat } from "next/font/google";
import Head from "next/head";

const monstserrat = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Darko | Create Designer and Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#cccc]">
        <h1 className="text-5xl font-bold">
          Welcome from the Next.Js Page Router
        </h1>
      </main>
    </div>
  );
}
